language: perl
perl:
  - "5.20-thr"

before_install: 
  - sudo apt-get update -qq
  - sudo apt-get install -qq blast2 libdb-dev libdb++-dev libxml2-dev zlib1g-dev
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - cpanm -n BioPerl
  - ./install_deps.sh

script: perl Makefile.PL && make test

after_failure: cat /home/travis/.cpanm/build.log

branches:
  only:
    - master
