language: perl
perl:
  - "5.20"
#  - "5.18"
#  - "5.16"
#  - "5.14"
#  - "5.12"
#  - "5.10"

before_install: 
  - sudo apt-get update -qq
  - sudo apt-get install -qq blast2 libdb-dev libdb++-dev libxml2-dev zlib1g-dev
  - cpanm -n BioPerl
  - ./install_deps.sh

script: perl Makefile.PL && make && prove -bv t/03-assemble.t

after_failure: ls -l /home/travis/build/sestaton/Chloro/src && ls -l /home/travis/build/sestaton/Chloro/src/VelvetOptimiser && ls -l /home/travis/build/sestaton/Chloro/src/velvet && ./home/travis/build/sestaton/Chloro/src/VelvetOptimiser/VelvetOptimiser.pl

branches:
  only:
    - master
