language: perl
perl:
  - "5.20"
#  - "5.18"
#  - "5.16"
#  - "5.14"
#  - "5.12"
#  - "5.10"

before_install: 
  - sudo apt-get update -qq
  - sudo apt-get install -qq blast2 libdb-dev libdb++-dev libxml2-dev zlib1g-dev
  - cpanm -n BioPerl
  - ./install_deps.sh

script: perl Makefile.PL && make && prove -bv t/03-assemble.t

after_failure: cd /home/travis/build/sestaton/Chloro && ./bin/chloro assemble -p t/test_data/t_cpseqs_screened_paired_interl.fas -s t/test_data/t_cpseqs_screened_unpaired.fas -i 59 -j 59

branches:
  only:
    - master
